### ISSUE TITLE
Ensure CKAN requests are made over HTTPS

### ISSUE THREAD

**Issue by gollyg** [govCMS/govcms-ckan#1]
_As a site administrator I want communications between my website and the CKAN datasource to be secure_

Configure the fetch module to ensure it is requesting data over https. This may be configurable (but should it really be?), but it should default to secure connections.

**Comment by jeremy-doghouse** [comment]
This already works for both http and https, it uses the base url protocol defined in the configuration page `admin/config/services/govcms-ckan`. If https is used here, all requests will be https. 

I don't think it should be forced to use https as there might be an occasion where this module is dealing with a non https endpoint?

**Comment by gollyg** [comment]
What about the case where you are using the api authentication? I think this should always be over https?

**Comment by jeremy-doghouse** [comment]
We could enforce https when validating the endpoint url if there is an API key present?

**Comment by gollyg** [comment]
Yeah, sounds like a good idea. We want that communication to be encrypted, even if the site is not running https.

**Comment by srowlands** [comment]
Resolved in #12
