### ISSUE TITLE
Ability to display x axis labels vertically

### ISSUE THREAD

**Issue by srowlands** [govCMS/govcms-ckan#27]
Some labels are too long to reasonably fit along the x axis horizontally. Include ability to rotate -90 degrees on existing visualisation types.

Should span multiple lines by default.

![unnamed](https://cloud.githubusercontent.com/assets/1256274/14374332/df5b3e5a-fd97-11e5-9d53-782395a4dd2b.gif)

**Comment by stooit** [comment]
In release/v1.0.0
