### ISSUE TITLE
Admin / content authoring process

### ISSUE THREAD

**Issue by brettyt** [govCMS/govcms-ckan#83]
Hi,
I'm seeking a little assistance for site builders/admins to "get started"/"up and running" using this module with data.gov.au/ckan website. Currently I'm running into problems knowing what steps need to taken before I get to publishing a graph using the web input.
From the point of view of never using CKAN before, if someone could provide a basic guide, or even a checklist, to at least get started. I can expand upon it to assist other govcms websites utilise this module.
This would be a big help to the community and ensure the module gets utilised effectively.
Thanks, Brett.

**Comment by jeremy-doghouse** [comment]
Hi @brettyt 

I do a pretty thorough walkthrough in this video https://youtu.be/_mJ8PRbVK0A?t=18m00s everything from uploading a CSV to CKAN all the way to creating and customising the graphs.

Long term, yes, would like to have some better documentation covering all aspects and options

**Comment by let17** [comment]
The video (at 19mins onwards) walks through just the part on adding content. Could you elaborate on the content type configurations. I have created a content type with file field that has a widget of media browser.

At the moment when adding content with the CKAN visualization set up as a table there is only a link visible to the dataset on data.gov.au. The table (or any of the charts) does not appear. Just checking what other configuration settings are needed.
