### ISSUE TITLE
The value for the 'keys' field on the Files form is empty

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/govcms-ckan#92]
The value for the 'keys' field on the Files form is empty. After fixing https://github.com/govCMS/govcms-ckan/issues/91 I can retrieve the data from the CKAN site, the other fields fill in with values from the dataset, however, the keys field remains empty. I've started stepping through the code, however, it would be handy if someone could point me to where $config['keys'] gets set.

**Comment by jeremy-doghouse** [comment]
Hey @kurtsalsa all config values get serialized and saved into a single blob
https://github.com/govCMS/govcms-ckan/blob/7.x-1.x/modules/govcms_ckan_media/includes/govcms_ckan_media.field_config.inc#L69

On loading the fields everything gets unserialized
https://github.com/govCMS/govcms-ckan/blob/7.x-1.x/modules/govcms_ckan_media/includes/govcms_ckan_media.field_config.inc#L86

**Comment by kurtfoster** [comment]
@jeremy-doghouse , the $items array is being passed in empty.

**Comment by kurtfoster** [comment]
@jeremy-doghouse , I'm still looking through this.

When i try this dataset from data.gov, the key values are filled in, however, $items in the functions you've listed are empty arrays. The lines listed above never run. The keys value, however, contains the correct values.

**Comment by jeremy-doghouse** [comment]
@kurtsalsa the only time that should be empty would be if it was a new entity on field_load. presave should always contain something. 

Maybe look at this function too: https://github.com/govCMS/govcms-ckan/blob/7.x-1.x/modules/govcms_ckan_media/includes/govcms_ckan_media.field_config.inc#L422 it handles displaying the keys

**Comment by kurtfoster** [comment]
@jeremy-doghouse , the issue ended up being with the data. The function I was looking for was this one, govcms_ckan_media_visualisation_default_key_config. The 'numeric' value for $key_type didn't match with the data. We've fixed the data instead.
